---
# tasks file for ngrok

- name: Install dependencies
  apt:
    state: present
    name: "{{ item }}"
    cache_valid_time: 3600
    update_cache: yes
  with_items:
      - unzip
      - apt-transport-https
      - python-pip
      - python-dev
      - libffi-dev
      - libssl-dev
      - curl

- name: Install python packages
  pip:
    state: latest
    name: "{{ item }}"
  with_items:
    - setuptools
    - urllib3
    - pyopenssl
    - ndg-httpsclient
    - pyasn1

- block:
    - name: Download Ngrok
      unarchive:
        src: "{{ ngrok_download_url }}"
        dest: /usr/local/bin/
        remote_src: yes
        owner: root
        group: root
        mode: '0744'

  rescue:
    - name: Download Ngrok with Curl
      command: >
        curl -o /tmp/ngrok.zip -L -O {{ ngrok_download_url }}
      args:
        creates: /tmp/ngrok.zip

    - name: Unzip and install Ngrok
      unarchive:
        src: /tmp/ngrok.zip
        dest: /usr/local/bin/
        remote_src: yes
        owner: root
        group: root
        mode: '0744'
